spring:
  profiles:
    active: local
---
server:
  port: 8182
  servlet:
    contextPath: /mapping-application

spring:
  application:
    name: mapping-application
    profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: root
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false